version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
    ports:
      - "2379:2379"
    networks:
      - patroni-net

  patroni1:
    image: zalando/patroni:latest
    container_name: patroni1
    environment:
      PATRONI_NAME: patroni1
      PATRONI_SCOPE: postgres-cluster
      PATRONI_RESTAPI_LISTEN: 0.0.0.0:8008
      PATRONI_RESTAPI_CONNECT_ADDRESS: patroni1:8008
      PATRONI_ETCD3_HOSTS: etcd:2379
      PATRONI_POSTGRESQL_LISTEN: 0.0.0.0:5101
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: patroni1:5101
      PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_SUPERUSER_PASSWORD: postgres
      PATRONI_REPLICATION_USERNAME: replicator
      PATRONI_REPLICATION_PASSWORD: replicator
    ports:
      - "5101:5432"
      - "8008:8008"
    networks:
      - patroni-net
    depends_on:
      - etcd

  patroni2:
    image: patroni/patroni:latest
    container_name: patroni2
    environment:
      PATRONI_NAME: patroni2
      PATRONI_SCOPE: postgres-cluster
      PATRONI_RESTAPI_LISTEN: 0.0.0.0:8008
      PATRONI_RESTAPI_CONNECT_ADDRESS: patroni2:8008
      PATRONI_ETCD3_HOSTS: etcd:2379
      PATRONI_POSTGRESQL_LISTEN: 0.0.0.0:5101
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: patroni2:5101
      PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_SUPERUSER_PASSWORD: postgres
      PATRONI_REPLICATION_USERNAME: replicator
      PATRONI_REPLICATION_PASSWORD: replicator
    ports:
      - "5102:5432"
      - "8009:8008"
    networks:
      - patroni-net
    depends_on:
      - etcd

  patroni3:
    image: patroni/patroni:latest
    container_name: patroni3
    environment:
      PATRONI_NAME: patroni3
      PATRONI_SCOPE: postgres-cluster
      PATRONI_RESTAPI_LISTEN: 0.0.0.0:8008
      PATRONI_RESTAPI_CONNECT_ADDRESS: patroni3:8008
      PATRONI_ETCD3_HOSTS: etcd:2379
      PATRONI_POSTGRESQL_LISTEN: 0.0.0.0:5101
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: patroni3:5101
      PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_SUPERUSER_PASSWORD: postgres
      PATRONI_REPLICATION_USERNAME: replicator
      PATRONI_REPLICATION_PASSWORD: replicator
    ports:
      - "5103:5432"
      - "8010:8008"
    networks:
      - patroni-net
    depends_on:
      - etcd

networks:
  patroni-net:
    driver: bridge